[package]
name = "window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.12.0"
winit = "0.28.3"
utils = { path = "../utils" }
wgpu = "0.15.1"
